### ISSUE TITLE
可不可以提供一下js的引入过程，ts的我的项目中不支持啊

### ISSUE THREAD

**Issue by ahualy** [Authing/authing-wxapp-sdk#10]
能详细提供一下小程序中使用authing时候使用js语法的引入过程吗，ts我的项目不支持，我发现咱们好多文档都是ts语法的

**Comment by zhaoyiming0803** [comment]
> 能详细提供一下小程序中使用authing时候使用js语法的引入过程吗，ts我的项目不支持，我发现咱们好多文档都是ts语法的

我们最近正在筹划重构小程序 SDK，会支持 TS 和 ESModule 规范，并且优化包体积。
